.TH "ALIYUN-IMG-UTILS" "1" "2025-05-19" "2.3.0" "aliyun-img-utils Manual"
.SH NAME
aliyun-img-utils \- The command line interface provides aliyun...
.SH SYNOPSIS
.B aliyun-img-utils
[OPTIONS] COMMAND [ARGS]...
.SH DESCRIPTION
.PP
    The command line interface provides aliyun image utilities.
.PP
    This includes uploading image tarballs and
    creating/publishing/deprecating framework images.
    
.SH OPTIONS
.TP
\fB\-\-version\fP
Show the version and exit.
.TP
\fB\-\-license\fP
Show license information.
.SH COMMANDS
.PP
\fBimage\fP
  Image commands.
  See \fBaliyun-img-utils-image(1)\fP for full documentation on the \fBimage\fP command.
